"""update ref_mess table

Revision ID: 0beaa2dc2a99
Revises: 707aec69a9b6
Create Date: 2024-11-27 13:06:13.612067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0beaa2dc2a99"
down_revision: Union[str, None] = "707aec69a9b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ref_start_text", sa.Column("ref_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ref_start_text", "ref_url")
    # ### end Alembic commands ###
