"""create galery table

Revision ID: 359386fd68dc
Revises: dd313f0e2432
Create Date: 2024-11-20 14:32:15.956626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "359386fd68dc"
down_revision: Union[str, None] = "dd313f0e2432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "img_galery",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("img_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("img_galery")
    # ### end Alembic commands ###
