"""create ref_mess table

Revision ID: 707aec69a9b6
Revises: ff2c8015ad07
Create Date: 2024-11-27 12:47:40.016895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "707aec69a9b6"
down_revision: Union[str, None] = "ff2c8015ad07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ref_start_text",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ref", sa.String(length=64), nullable=False),
        sa.Column("en", sa.String(), nullable=False),
        sa.Column("ua", sa.String(), nullable=False),
        sa.Column("ru", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ref_start_text")
    # ### end Alembic commands ###
